---
title: "methods-results"
format: html
---

# Study 1
## Item Generation
Item generation was undertaken in several stages. The first step in item generation consisted of items generated in two scales (harm reduction principles and harm reduction strategies) which were drafted by the authors and piloted with harm reduction workers in local training and harm reduction supply distribution evaluation. Following the initial pilot project, we revised and added items to address gaps that had been noted. The items were generated with regard to both the SAMHSA Harm Reduction Framework and the National Harm Reduction Coalation's Harm Reduction Principles(\href{https://harmreduction.org/about-us/principles-of-harm-reduction/}{link}). Once the initial item pool was generated, we consulted with Dr. David Frank, a harm reduction expert and researcher. Based on his consultation, items were futher modified to be accessable to a general popuation. 
We used Wolf et al's (2023) Response Process Evaluation (RPE) method to ensure that a non-expert, non-harm reduction audiance would understand the item content. Over X rounds of data collection, we used Prolific to collect qualitative responses to each item. As a group, we evaluated each set of responses to determine whether respondents understood or did not understand the intended meaning of each item. Based on respondent answers and suggestions, we identified items which items were generally understood, and which items should be modified or removed. The RPE data, item information and intended meanings, and author codings are available at \href{osf.io}{osf link goes here}. Table 1 contains the final items that were used for the initial round of quantitative data collection.
This item pool contains X items related to harm reduction strategies and Y items related to harm reduction principals. There are z total reverse scored items (x in scale 1, y in scale 2). These items cover a, b, c, consepts relate to harm reduction practice. We phrased strategy items to ask about respondents moral assessment of the practic occuring, rather than to ask about the approval of the actual practice. We phrased the principal items as simply and directly as possible, occasionally splitting complex topics (experiences of discrimination, other topic) across multiple items when necessary. 
The aim of study 1 is to identify items to retain in future scales and scale factor structure.
## Methods
We recurited x participants from Prolific.